### ISSUE TITLE
function to download NIHOCC data in your python notebooks doesn't work

### ISSUE THREAD

**Issue by pnguyen-biotech** [dvklopfenstein/pmidcite#2]
I downloaded two python notebooks and both functions api.dnld_icite and dnldr.get_icite gives the same error:
![Capture](https://user-images.githubusercontent.com/80936944/125205835-3c316d80-e252-11eb-852a-ce972b43cb5a.PNG)

**Comment by dvklopfenstein** [comment]
@pnguyen-biotech,

Thank you so much for your interest in pmidcite, for taking your time to open this issue, and to include important details for debugging.

I have updated the notebook, NIHOCC_data_download_always.ipynb, so that it uses NIH Grouper. The new NIH Grouper object allows researchers to change the dividing percentiles used for grouping.

Grouping helps researchers sort through large lists of PMIDs by putting papers that are performing well or are new at the front of the list and putting papers that are in the lowest percentila (below the 15.7th percentile of the paper's co-citation network) at the back of a sorted list.

I recently made the grouping customizable by the researcher by adding a new NIH Grouper object.

Thank you so much for alerting me to this issue. I will update the remainder of the notebooks shortly.

**Comment by dvklopfenstein** [comment]
I updated all the notebooks and created a new PyPi version. Please download and try again. If there are any problems, please feel free to open a new issue.

Thank you so much for taking your time to write and open this issue. Your comments were extremely helpful.

**Comment by dvklopfenstein** [comment]
@pnguyen-biotech,

Please note that I have simplified the pmidcite library interface. Now to instantiate a NIHiCiteDownloader, do this:

```
from pmidcite.icite.pmid_dnlder import NIHiCiteDownloader

dnldr = NIHiCiteDownloader('./icite', force_download=True)
```

The interface was formerly:

```
from pmidcite.icite.api import NIHiCiteAPI
from pmidcite.icite.nih_grouper import NihGrouper
from pmidcite.icite.pmid_dnlder import NIHiCiteDownloader

grpr = NihGrouper()
api = NIHiCiteAPI(grpr, './icite')
force_download = False
dnldr = NIHiCiteDownloader(force_download, api)
```

cc: @aditya-sarkar441
